function(tristate NAME DESCRIPTION)
	set(oneValueArgs DEFAULT)
	cmake_parse_arguments(PARSE_ARGV 0 arg "" "${oneValueArgs}" "")

	if(NOT arg_DEFAULT)
		set(arg_DEFAULT "AUTO")
	endif()

	set(${NAME} ${arg_DEFAULT} CACHE STRING "${DESCRIPTION}")
	set_property(CACHE ${NAME} PROPERTY STRINGS AUTO ON OFF)
	set_property(CACHE ${NAME} PROPERTY HELPSTRING "${DESCRIPTION}")
endfunction()
function(tristate_package STATE PACKAGE)
	set(multiValueArgs ARGS DEFINE)
	cmake_parse_arguments(PARSE_ARGV 0 arg "" "" "${multiValueArgs}")
	get_property(docstring CACHE ${STATE} PROPERTY "HELPSTRING")
	if(${STATE} STREQUAL "AUTO")
		find_package(${PACKAGE} ${ARGS})
		if(${PACKAGE}_FOUND)
			set(${STATE} ON)
		endif()
		message(STATUS "${docstring}: AUTO (${${STATE}})")
	elseif(${STATE})
		find_package(${PACKAGE} ${ARGS} REQUIRED)
		message(STATUS "${docstring}: YES")
	else()
		message(STATUS "${docstring}: NO")
	endif()
	if(${PACKAGE}_FOUND)
		foreach(define IN ITEMS arg_DEFINE)
			add_compile_definitions(${define})
		endforeach()
	endif()
endfunction()
